name: Auto Deploy
on: [push]
jobs:
  Deploy-Github-Pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run "yarn run deploy" command
      - run: yarn
      - run: yarn run deploy
      - run: echo "ğŸ This job's status is ${{ job.status }}."
